### ISSUE TITLE
Change require httplug to v2.0

### ISSUE THREAD

**Issue by strausmann** [packagist/private-packagist-api-client#12]
Hi guys,

Is there anything against an upgrade for httplug to the version > 2.0.0?

Regards,

Bjoern

**Comment by glaubinix** [comment]
The main reason why we didn't upgrade to 2.0 is that we want to make sure this still runs on php 5.6. But happy to support php-http/httplug version 1 and 2.

**Comment by glaubinix** [comment]
Had a quick look at this. There are still some php-http packages which don't have a stable release yet supporting 2.0 for instance https://packagist.org/packages/php-http/client-common.

Will revisit this at a later point.

**Comment by glaubinix** [comment]
This has been implemented and released with https://github.com/packagist/private-packagist-api-client/releases/tag/1.16.0.
