### ISSUE TITLE
Using packageName in the API results in "Access Denied" error

### ISSUE THREAD

**Issue by QassaDevelopers** [packagist/private-packagist-api-client#21]
We have a fully operational private packagist running. Adding packages through composer or adding them manual works like a charm.

We are using your package (`packagist/private-packagist-api-client`) to communicate with the private packagist's API.

However, when using this API, we get an error when using specific API endpoints. More specifically, the `GET /api/ackages/{packageName}` and the `POST /api/packages/{packageName}`.

Given this piece of example code:
```php
<?php

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

$privatePackagistUrl = '';
$apiToken = '';
$apiSecret = '';

$client = new \PrivatePackagist\ApiClient\Client(null, $privatePackagistUrl);
$client->authenticate($apiToken, $apiSecret);
$packages = $client->packages()->all();
/**
 * print_r($packages);
 * (
 *     [0] => Array
 *         (
 *             [name] => symfony/console
 *             [origin] => public-proxy
 *             [credentials] => 
 *             [links] => Array
 *                 (
 *                     [self] => /api/packages/symfony/console/
 *                 )
 * 
 *         )
 * 
 * )
 */

$client = new \PrivatePackagist\ApiClient\Client(null, $privatePackagistUrl);
$client->authenticate($apiToken, $apiSecret);
$package = $client->packages()->show('symfony/console');
// Fatal error: Uncaught PrivatePackagist\ApiClient\Exception\RuntimeException: Access Denied.
```

This results in a fatal error:
```
PHP Fatal error:  Uncaught PrivatePackagist\ApiClient\Exception\RuntimeException: Access Denied. in /[dir]/vendor/private-packagist/api-client/src/HttpClient/Plugin/ExceptionThrower.php:41
Stack trace:
#0 /[dir]/vendor/php-http/httplug/src/Promise/HttpFulfilledPromise.php(34): PrivatePackagist\ApiClient\HttpClient\Plugin\ExceptionThrower->PrivatePackagist\ApiClient\HttpClient\Plugin\{closure}(Object(GuzzleHttp\Psr7\Response))
#1 /[dir]/vendor/private-packagist/api-client/src/HttpClient/Plugin/ExceptionThrower.php(42): Http\Client\Promise\HttpFulfilledPromise->then(Object(Closure))
#2 /[dir]/vendor/php-http/client-common/src/Pl in /[dir]/vendor/private-packagist/api-client/src/HttpClient/Plugin/ExceptionThrower.php on line 41
```

The response returned by the API is:
```
string(109) "{"status":"error","message":"Access Denied.","documentationUrl":"[packagist-url]\/docs\/api"}"
```

The API credentials I use are good, the first API call (and other API calls for that matter) give proper responses. It is the `show()` and `editVcsPackage()` methods that fail.

I suspect it has something to do with the slash in the packageName, but escaping this did not help.

Could you perhaps see what I am doing wrong, or confirm that this is a bug?

**Comment by glaubinix** [comment]
Thank you for this very detailed report. Some of our endpoints are restricted based on what features you are using on Private Packagist. The Access Denied error sounds like your organization does not have access to those endpoints. Would you mind reaching out to us either via support chat on the website or via email to contact(at)packagist.com with your Organization name? I'd be more than happy to have a closer look at it.

**Comment by QassaDevelopers** [comment]
Thanks for your reply. I forgot to mention that we run a self-hosted enterprise version of private packagist. We are still in the trial period.

Perhaps this gives you new insights? Otherwise I will contact support.

**Comment by QassaDevelopers** [comment]
I have contacted support. The reason for these errors is that the Enterprise version of Private Packagist does not have the API's enabled. Support said they will be enabled in a future release.
