### ISSUE TITLE
Move from `php-http/client-implementation` to `psr/http-client-implementation`

### ISSUE THREAD

**Issue by Kingdutch** [packagist/private-packagist-api-client#52]
As per https://github.com/php-http/httplug

> New client implementations and consumers should use the PSR-18 interfaces directly. In the long term, we expect PSR-18 to completely replace the need for HTTPlug.

For projects using `guzzlehttp/guzzle` in version 7 or higher this removes the need to also require `php-http/guzzle7-adapter`.

**Comment by glaubinix** [comment]
Hey @Kingdutch changes for this have just been added to the master branch. We'll try this with a couple of different HTTP clients and if nothing comes up, release this later this week. I'll keep you posted.

**Comment by glaubinix** [comment]
This has been release as 1.28.0
